/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "terms.show": [],
    "policy.show": [],
    "profile.show": [],
    "other-browser-sessions.destroy": [],
    "current-user-photo.destroy": [],
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "beneficiaries.index": [],
    "beneficiaries.create": [],
    "beneficiaries.store": [],
    "beneficiaries.show": [
        {
            "name": "beneficiary",
            "required": true
        }
    ],
    "beneficiaries.edit": [
        {
            "name": "beneficiary",
            "required": true
        }
    ],
    "beneficiaries.update": [
        {
            "name": "beneficiary",
            "required": true
        }
    ],
    "beneficiaries.destroy": [
        {
            "name": "beneficiary",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
